#!/bin/bash
# Wrap the rootfs tarball produced by build.sh into a flashable disk image.
#
# Output: out/iam-os-<version>-<arch>.img(.gz)
#
# Layout (GPT):
#   Partition 1: ESP (FAT32, ~128 MiB) — boots via systemd-boot.
#   Partition 2: Linux root (ext4, rest) — the rootfs tarball, extracted.
#
# Boot path: UEFI firmware → systemd-boot (stage1 in ESP/EFI/BOOT/) →
# the kernel + initrd written to the ESP → root mounted by PARTUUID.
# bootctl runs inside the rootfs chroot so the image's own systemd-boot
# binary is the one installed; this avoids version skew with the runner
# host's systemd.
#
# Needs root (losetup, mount, mkfs). Uses sudo internally so a regular
# developer or a CI runner with passwordless sudo can invoke it. Linux
# only — losetup, parted, mkfs.fat, and bootctl are Linux-specific.

set -euo pipefail

VERSION="${IAM_OS_VERSION:-dev}"
ARCH="${IAM_OS_ARCH:-amd64}"
OUT_DIR="${OUT_DIR:-out}"
IMG_SIZE="${IAM_OS_IMG_SIZE:-2GiB}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_ROOT="$REPO_ROOT/$OUT_DIR"
ROOTFS="$OUT_ROOT/iam-os-${VERSION}-${ARCH}-rootfs.tar.gz"
IMG="$OUT_ROOT/iam-os-${VERSION}-${ARCH}.img"

note() { printf '[make-image] %s\n' "$*"; }
fail() { printf '[make-image] error: %s\n' "$*" >&2; exit 1; }

[ "$(uname -s)" = "Linux" ] || fail "Linux only (host is $(uname -s))"
[ -f "$ROOTFS" ] || fail "rootfs missing: $ROOTFS (run build.sh first)"
for cmd in parted losetup mkfs.fat mkfs.ext4 sgdisk; do
    command -v "$cmd" >/dev/null 2>&1 || fail "missing tool: $cmd"
done

WORKDIR="$(mktemp -d)"
LOOP=""

cleanup() {
    set +e
    if [ -n "$LOOP" ]; then
        for m in /boot/efi /dev /proc /sys /run; do
            sudo umount "$WORKDIR/root$m" 2>/dev/null
        done
        sudo umount "$WORKDIR/root" 2>/dev/null
        sudo losetup -d "$LOOP" 2>/dev/null
    fi
    rm -rf "$WORKDIR"
}
trap cleanup EXIT

mkdir -p "$WORKDIR/root" "$OUT_ROOT"

note "creating raw image at $IMG ($IMG_SIZE)"
rm -f "$IMG"
truncate -s "$IMG_SIZE" "$IMG"

note "partitioning (GPT, ESP + root)"
sudo parted -s "$IMG" mklabel gpt
sudo parted -s "$IMG" mkpart ESP fat32 1MiB 129MiB
sudo parted -s "$IMG" set 1 esp on
sudo parted -s "$IMG" mkpart root ext4 129MiB 100%

note "attaching loop device"
LOOP="$(sudo losetup -fP --show "$IMG")"
ESP_PART="${LOOP}p1"
ROOT_PART="${LOOP}p2"

note "formatting partitions"
sudo mkfs.fat -F32 -n IAM_ESP "$ESP_PART" >/dev/null
sudo mkfs.ext4 -F -L iam-root "$ROOT_PART" >/dev/null

ROOT_PARTUUID="$(sudo blkid -s PARTUUID -o value "$ROOT_PART")"
note "root PARTUUID=$ROOT_PARTUUID"

note "extracting rootfs"
sudo mount "$ROOT_PART" "$WORKDIR/root"
sudo tar -xpf "$ROOTFS" -C "$WORKDIR/root"

sudo mkdir -p "$WORKDIR/root/boot/efi"
sudo mount "$ESP_PART" "$WORKDIR/root/boot/efi"

note "writing /etc/fstab"
sudo tee "$WORKDIR/root/etc/fstab" >/dev/null <<EOF
# Generated by os-image/make-image.sh.
PARTUUID=$ROOT_PARTUUID  /          ext4   defaults,relatime  0  1
LABEL=IAM_ESP            /boot/efi  vfat   umask=0077         0  2
EOF

note "binding /dev /proc /sys /run for chroot"
for m in dev proc sys run; do
    sudo mount --bind "/$m" "$WORKDIR/root/$m"
done

note "installing systemd-boot via chroot bootctl"
sudo chroot "$WORKDIR/root" bootctl install --no-variables

KERNEL="$(sudo ls "$WORKDIR/root/boot" | grep '^vmlinuz' | sort -V | tail -1)"
INITRD="$(sudo ls "$WORKDIR/root/boot" | grep '^initrd.img' | sort -V | tail -1)"
[ -n "$KERNEL" ] || fail "no kernel found in /boot — build.sh must include linux-image-amd64"
[ -n "$INITRD" ] || fail "no initrd found in /boot"
note "kernel: $KERNEL, initrd: $INITRD"

note "copying kernel + initrd to ESP"
sudo cp "$WORKDIR/root/boot/$KERNEL" "$WORKDIR/root/boot/efi/$KERNEL"
sudo cp "$WORKDIR/root/boot/$INITRD" "$WORKDIR/root/boot/efi/$INITRD"

note "writing systemd-boot loader configuration"
sudo tee "$WORKDIR/root/boot/efi/loader/loader.conf" >/dev/null <<EOF
default iam-os
timeout 1
console-mode max
editor no
EOF

sudo mkdir -p "$WORKDIR/root/boot/efi/loader/entries"
sudo tee "$WORKDIR/root/boot/efi/loader/entries/iam-os.conf" >/dev/null <<EOF
title    IAM-OS $VERSION
linux    /$KERNEL
initrd   /$INITRD
options  root=PARTUUID=$ROOT_PARTUUID ro console=tty0 console=ttyS0,115200n8 systemd.show_status=yes
EOF

note "syncing and unmounting"
sudo sync
for m in run sys proc dev; do
    sudo umount "$WORKDIR/root/$m"
done
sudo umount "$WORKDIR/root/boot/efi"
sudo umount "$WORKDIR/root"
sudo losetup -d "$LOOP"
LOOP=""

note "compressing image"
gzip -f "$IMG"
note "image: ${IMG}.gz"
ls -lh "${IMG}.gz"
